// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avmbtikrdufrrdpgrqgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2bWJ0aWtyZHVmcnJkcGdycWd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzU1ODksImV4cCI6MjA2NTUxMTU4OX0.HLZkzgQXrMuv36KKHLznozxjJ849BlEAyZHIPydQ6Pk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);